# Enable C++ support
language: cpp
os: windows
env:
- LABEL="windows-msvc"
- MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
script:
- export PATH=$MSBUILD_PATH:$PATH
- ls -al "/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/"
- msbuild.exe ja2_VS2017.sln
